name: socialverse
description: SocialVerse is a blazing a new social frontier of long-form mobile videos.A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.4+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.0
  camera: ^0.10.0+3
  charts_flutter: ^0.12.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  extended_image: ^7.0.2
  firebase_core: ^2.5.0
  firebase_dynamic_links: ^5.0.12
  flutter_datetime_picker: ^1.5.1
  flutter_radar_chart: ^0.2.1
  flutter_svg: ^2.0.1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.9
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  lottie: ^2.2.0
  move_to_background: ^1.0.2
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  permission_handler: ^10.1.0
  # pip_flutter: ^0.0.3
  share_plus: ^6.3.1
  shimmer: ^2.0.0
  uuid: ^3.0.6
  video_player: ^2.3.0
  pie_menu: ^1.2.2
  syncfusion_flutter_sliders: ^20.1.55
  timeago: ^3.2.0
  wechat_assets_picker: ^8.1.3
  url_launcher: ^6.1.3
  webview_flutter: ^4.0.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  screenshot: ^1.2.2
  image_gallery_saver: ^1.7.1
  preload_page_view: ^0.1.6
  image_cropper: ^3.0.0
  unicons: ^2.1.0
  expandable_text: ^2.3.0
  flutter_screenutil: ^5.5.3+2
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0
  firebase_auth: ^4.2.10
  eva_icons_flutter: ^3.1.0
  crypto: ^3.0.2
  flutter_facebook_auth: ^5.0.8
  

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.2
  change_app_package_name: ^1.1.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/gif/
    - assets/svg/

  fonts:
    - family: sofia
      fonts:
        - asset: assets/fonts/sofia.otf
