//common Import
export 'dart:convert';
export 'dart:async';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export '../../app.dart';
export 'package:socialverse/core/widgets/appbar.dart';
export 'package:socialverse/core/utils/ui.dart';
export 'package:socialverse/core/utils/app_text_style.dart';
export 'package:socialverse/core/utils/app_asset.dart';
export 'package:socialverse/core/utils/app_constants.dart';
export 'package:image_cropper/image_cropper.dart';
export 'package:socialverse/core/utils/custom_progress_indicator.dart';
export 'package:socialverse/core/utils/bottom_sheet.dart';
export 'package:socialverse/core/network/network_repository.dart';
export 'package:socialverse/core/utils/custom_progress_indicator.dart';
export 'package:socialverse/core/widgets/error_dialog.dart';
export 'package:socialverse/core/widgets/buttons/text_button.dart';
export 'package:socialverse/core/widgets/textfields/text_widget.dart';
export 'package:socialverse/core/widgets/textfields/input_text_field_widget.dart';
export 'package:socialverse/core/widgets/common_widget.dart';
export 'package:socialverse/feature/home/extension/timegao.dart';
export 'package:socialverse/core/helpers/image_helper.dart';

export 'package:socialverse/core/utils/colors.dart';
export 'package:socialverse/feature/wallet/comming_soon_screen.dart';
export 'package:socialverse/core/utils/static_decoration.dart';
export 'package:socialverse/core/widgets/textfields/text_widget.dart';
export 'package:socialverse/core/widgets/image_widget.dart';
export 'package:socialverse/core/utils/custom_progress_indicator.dart';

// Screen
export 'package:socialverse/feature/home/widgets/comment_widget.dart';
export 'package:socialverse/feature/home/views/home_screen.dart';
export 'package:socialverse/core/utils/bottom_sheet.dart';
export 'feature/profile/views/profile_screen.dart';
export 'feature/search/views/sphere_screen.dart';
export 'feature/wallet/wallet_screen.dart';
export 'package:socialverse/core/widgets/appbar.dart';
export 'package:socialverse/feature/auth/views/login_screen.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:move_to_background/move_to_background.dart';
// export 'package:pip_flutter/pipflutter_player.dart';
// export 'package:pip_flutter/pipflutter_player_configuration.dart';
// export 'package:pip_flutter/pipflutter_player_controller.dart';
// export 'package:pip_flutter/pipflutter_player_controls_configuration.dart';
// export 'package:pip_flutter/pipflutter_player_data_source.dart';
// export 'package:pip_flutter/pipflutter_player_data_source_type.dart';
// export 'package:pip_flutter/pipflutter_player_event.dart';
// export 'package:pip_flutter/pipflutter_player_event_type.dart';
export 'package:socialverse/core/widgets/buttons/icon_button.dart';
export 'package:socialverse/feature/chats/views/chat_screen.dart';
export 'package:socialverse/feature/notifications/views/notification_screen.dart';
export 'package:socialverse/feature/profile/views/settings/settings_screen.dart';
export 'package:socialverse/feature/profile/views/edit_profile/edit_profile_screen.dart';
export 'package:socialverse/feature/profile/views/follower/follower_screen.dart';
export 'package:socialverse/feature/profile/views/following/following_screen.dart';
export 'package:socialverse/feature/profile/widgets/post_grid_widget.dart';
export 'package:socialverse/feature/search/views/sphere_screen.dart';
export 'package:socialverse/feature/search/widgets/spheres_search_grid_widget.dart';
export 'package:socialverse/feature/search/widgets/account_search_grid.dart';
export 'package:socialverse/feature/search/widgets/post_search_widget.dart';
export 'package:socialverse/feature/create/views/editor_screen.dart';
export 'package:socialverse/feature/search/widgets/hashtag_search_widget.dart';
export 'package:socialverse/feature/search/views/create_sphere/create_sphere_screen.dart';
export 'package:socialverse/feature/search/views/category_screen.dart';
//common Import
export 'dart:convert';
export 'dart:async';
// export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export '../../app.dart';
export 'package:socialverse/core/widgets/appbar.dart';
export 'package:socialverse/core/utils/ui.dart';
export 'package:socialverse/core/utils/app_text_style.dart';
export 'package:socialverse/core/utils/app_asset.dart';
export 'package:socialverse/core/utils/app_constants.dart';
// export 'package:socialverse/src/utils/validator.dart';
export 'package:socialverse/core/utils/custom_progress_indicator.dart';
export 'package:socialverse/core/utils/bottom_sheet.dart';
export 'package:socialverse/core/network/network_repository.dart';
export 'package:socialverse/core/utils/custom_progress_indicator.dart';
export 'package:socialverse/core/widgets/error_dialog.dart';
export 'package:socialverse/core/widgets/buttons/text_button.dart';
export 'package:socialverse/core/widgets/textfields/text_widget.dart';
export 'package:socialverse/core/widgets/textfields/input_text_field_widget.dart';
export 'package:socialverse/core/widgets/common_widget.dart';

export 'package:socialverse/core/utils/colors.dart';
export 'package:socialverse/feature/wallet/comming_soon_screen.dart';
export 'package:socialverse/core/utils/static_decoration.dart';
export 'package:socialverse/core/widgets/textfields/text_widget.dart';
export 'package:socialverse/core/widgets/image_widget.dart';
export 'package:socialverse/core/utils/custom_progress_indicator.dart';
export 'package:socialverse/feature/search/controllers/create_sphere_controller.dart';

// Screen
export 'package:socialverse/feature/home/widgets/comment_widget.dart';
export 'package:socialverse/feature/home/views/home_screen.dart';
export 'package:socialverse/core/utils/bottom_sheet.dart';
export 'package:socialverse/core/views/report/report_page.dart';
export 'feature/profile/views/profile_screen.dart';
export 'feature/search/views/sphere_screen.dart';
export 'feature/wallet/wallet_screen.dart';
export 'package:socialverse/core/widgets/appbar.dart';
export 'package:socialverse/feature/auth/views/login_screen.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:move_to_background/move_to_background.dart';
// export 'package:pip_flutter/pipflutter_player.dart';
// export 'package:pip_flutter/pipflutter_player_configuration.dart';
// export 'package:pip_flutter/pipflutter_player_controller.dart';
// export 'package:pip_flutter/pipflutter_player_controls_configuration.dart';
// export 'package:pip_flutter/pipflutter_player_data_source.dart';
// export 'package:pip_flutter/pipflutter_player_data_source_type.dart';
// export 'package:pip_flutter/pipflutter_player_event.dart';
// export 'package:pip_flutter/pipflutter_player_event_type.dart';
export 'package:socialverse/core/widgets/buttons/icon_button.dart';
export 'package:socialverse/feature/chats/views/chat_screen.dart';
export 'package:socialverse/feature/notifications/views/notification_screen.dart';
export 'package:socialverse/feature/profile/views/settings/settings_screen.dart';
export 'package:socialverse/core/views/splash/splash_screen.dart';
export 'package:socialverse/feature/profile/views/edit_profile/edit_profile_screen.dart';
export 'package:socialverse/feature/profile/views/follower/follower_screen.dart';
export 'package:socialverse/feature/profile/views/following/following_screen.dart';
export 'package:socialverse/feature/profile/widgets/post_grid_widget.dart';
export 'package:socialverse/feature/search/views/sphere_screen.dart';
export 'package:socialverse/feature/search/widgets/spheres_search_grid_widget.dart';
export 'package:socialverse/feature/search/widgets/account_search_grid.dart';
export 'package:socialverse/feature/search/widgets/post_search_widget.dart';
export 'package:socialverse/feature/create/views/editor_screen.dart';
export 'package:socialverse/feature/create/views/post_screen.dart';
export 'package:socialverse/core/views/main_home_screen.dart';
export 'core/utils/network_dio.dart';
export 'package:socialverse/feature/auth/views/signup_screen.dart';
export 'package:socialverse/feature/auth/views/login_screen.dart';
export 'package:socialverse/feature/auth/views/forgot_password_screen.dart';
export 'package:socialverse/feature/auth/controllers/reset_password_controller.dart';
export 'package:socialverse/feature/search/views/search_screen.dart';
export 'package:socialverse/feature/search/widgets/spheres_widget.dart';
export 'package:socialverse/feature/search/views/edit_sphere/edit_sphere.dart';

//Controller
export 'package:socialverse/feature/home/controllers/video_player_controller.dart';
export 'package:socialverse/feature/home/controllers/comment_controller.dart';
export 'package:socialverse/feature/home/controllers/home_controller.dart';
export 'package:socialverse/feature/auth/controllers/login_controller.dart';
export 'package:socialverse/core/controllers/main_home_screen_controller.dart';
export 'package:socialverse/feature/create/controllers/editor_controller.dart';
export 'package:socialverse/feature/profile/controllers/profile_controller.dart';
export 'package:socialverse/feature/profile/controllers/follower_controller.dart';
export 'package:socialverse/feature/chats/controllers/chat_controller.dart';
export 'package:socialverse/feature/create/controllers/post_controller.dart';
export 'package:socialverse/feature/profile/controllers/my_algo_controller.dart';
export 'package:socialverse/feature/profile/controllers/setting_controller.dart';
export 'package:socialverse/feature/profile/controllers/edit_profile_controller.dart';
export 'package:socialverse/feature/profile/controllers/following_controller.dart';
export 'package:socialverse/core/controllers/theme_controller.dart';
export 'package:socialverse/feature/auth/controllers/login_controller.dart';
export 'package:socialverse/feature/auth/controllers/signup_controller.dart';
export 'package:socialverse/feature/search/controllers/search_controller.dart';
export 'package:socialverse/feature/home/controllers/home_video_player.controller.dart';

//Package
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:socialverse/core/utils/internet_error.dart';
export 'package:dio_http_cache/dio_http_cache.dart';
export 'package:flutter_radar_chart/flutter_radar_chart.dart';
export 'package:shimmer/shimmer.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:share_plus/share_plus.dart';
export 'package:socialverse/feature/home/widgets/video_player_widget.dart';
export 'package:move_to_background/move_to_background.dart';
// export 'package:pip_flutter/pipflutter_player_controller.dart';
// export 'package:pip_flutter/pipflutter_player_data_source.dart';
// export 'package:pip_flutter/pipflutter_player_data_source_type.dart';
export 'package:video_player/video_player.dart';
export 'package:get_storage/get_storage.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:awesome_dialog/awesome_dialog.dart';
export 'package:get_storage/get_storage.dart';
export 'package:flutter_svg/svg.dart';
export 'package:camera/camera.dart';
export 'package:image_picker/image_picker.dart';
export 'package:percent_indicator/circular_percent_indicator.dart';
export 'package:flutter_switch/flutter_switch.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:socialverse/feature/create/views/post_screen.dart';
export 'package:socialverse/core/views/main_home_screen.dart';
export 'package:socialverse/core/views/welcome/welcome_screen.dart';
export 'core/utils/network_dio.dart';
export 'package:socialverse/feature/auth/views/signup_screen.dart';
export 'package:socialverse/feature/auth/views/login_screen.dart';
export 'package:socialverse/feature/auth/views/forgot_password_screen.dart';
export 'package:socialverse/feature/auth/controllers/reset_password_controller.dart';

//Controller
export 'package:socialverse/feature/home/controllers/video_player_controller.dart';
export 'package:socialverse/feature/home/controllers/comment_controller.dart';
export 'package:socialverse/feature/home/controllers/home_controller.dart';
export 'package:socialverse/feature/auth/controllers/login_controller.dart';
export 'package:socialverse/core/controllers/main_home_screen_controller.dart';
export 'package:socialverse/feature/create/controllers/editor_controller.dart';
export 'package:socialverse/feature/profile/controllers/profile_controller.dart';
export 'package:socialverse/feature/profile/controllers/follower_controller.dart';
export 'package:socialverse/feature/chats/controllers/chat_controller.dart';
export 'package:socialverse/feature/create/controllers/post_controller.dart';
export 'package:socialverse/feature/profile/controllers/my_algo_controller.dart';
export 'package:socialverse/feature/profile/controllers/setting_controller.dart';
export 'package:socialverse/feature/profile/controllers/edit_profile_controller.dart';
export 'package:socialverse/feature/profile/controllers/following_controller.dart';
export 'package:socialverse/core/controllers/theme_controller.dart';
export 'package:socialverse/feature/auth/controllers/login_controller.dart';
export 'package:socialverse/feature/auth/controllers/signup_controller.dart';
export 'package:socialverse/feature/search/controllers/search_controller.dart';
export 'package:socialverse/feature/search/controllers/edit_sphere_controller.dart';

//Package
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:socialverse/core/utils/internet_error.dart';
export 'package:dio_http_cache/dio_http_cache.dart';
export 'package:flutter_radar_chart/flutter_radar_chart.dart';
export 'package:shimmer/shimmer.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:share_plus/share_plus.dart';
export 'package:socialverse/feature/home/widgets/video_player_widget.dart';
export 'package:socialverse/feature/home/widgets/home_video_widget.dart';
export 'package:move_to_background/move_to_background.dart';
// export 'package:pip_flutter/pipflutter_player_controller.dart';
// export 'package:pip_flutter/pipflutter_player_data_source.dart';
// export 'package:pip_flutter/pipflutter_player_data_source_type.dart';
export 'package:get_storage/get_storage.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:awesome_dialog/awesome_dialog.dart';
export 'package:get/get.dart';
export 'package:get_storage/get_storage.dart';
export 'package:flutter_svg/svg.dart';
export 'package:camera/camera.dart';
export 'package:image_picker/image_picker.dart';
export 'package:percent_indicator/circular_percent_indicator.dart';
export 'package:flutter_switch/flutter_switch.dart';
