// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgq5BlWQ9YyJcLWobVsSU-HwQ1KCesomk',
    appId: '1:115873070240:android:e3b603322ed05e25299dc5',
    messagingSenderId: '115873070240',
    projectId: 'flic-69356',
    storageBucket: 'flic-69356.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBzayDUG4lZhpTkF-CW0jKH1vpTPzpDpQ',
    appId: '1:115873070240:ios:4a782731fdbf7f40299dc5',
    messagingSenderId: '115873070240',
    projectId: 'flic-69356',
    storageBucket: 'flic-69356.appspot.com',
    androidClientId: '115873070240-3mmbq5jb5bh8ecg6je9b4a3b2tb6ajqo.apps.googleusercontent.com',
    iosClientId: '115873070240-6c0ii7il1il6hod49c1m9q503sof8v07.apps.googleusercontent.com',
    iosBundleId: 'com.subverse.whitepill',
  );
}
